{
 "title": "Infrastructure Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "KavaNetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align:center\">Master Node</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align:center\">\n  Worker Node\n</h1>"
   }
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"192.168.1.42:9100\",job=\"K3S\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.1.42:9100\",job=\"K3S\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"192.168.1.42:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"192.168.1.43:9100\",job=\"K3S\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.1.43:9100\",job=\"K3S\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"192.168.1.43:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.1.42:9100\",job=\"K3S\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.1.43:9100\",job=\"K3S\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.1.42:9100\",job=\"K3S\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"192.168.1.42:9100\",job=\"K3S\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"192.168.1.42:9100\",job=\"K3S\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.1.43:9100\",job=\"K3S\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"192.168.1.43:9100\",job=\"K3S\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"192.168.1.43:9100\",job=\"K3S\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.42:9100\",job=\"K3S\"}",
     "legendFormat": "{{sensor }} "
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.43:9100\",job=\"K3S\"}",
     "legendFormat": "{{sensor }} "
    }
   ]
  }
 ]
}