{
 "title": "Hardware Status",
 "tags": [ "KavaNet" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "master", "query": "192.168.1.42" },
   { "name": "heavy", "query": "192.168.1.43" },
   { "name": "KavaNas", "query": "192.168.1.50" },
   { "name": "Light", "query": "192.168.1.11" },
   { "name": "NetworkController", "query": "192.168.1.45" },
   { "name": "KavaNet", "query": "192.168.1.46" }
  ]
 },
 "panels": [
  { "title": "KavaNetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">Master Node</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">Worker</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">Registry\n</h1>"
   }
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$master:9100\",job=\"K3S\"}",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$master:9100\",job=\"K3S\",sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$heavy:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$heavy:9100\",job=\"K3S\"}",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$heavy:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$heavy:9100\",job=\"K3S\",sensor=\"temp0\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$master:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$master:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$master:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$heavy:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$heavy:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$heavy:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$heavy:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$heavy:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$heavy:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$heavy:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$master:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$master:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$master:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$heavy:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$heavy:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$heavy:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$heavy:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$heavy:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$heavy:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$heavy:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  { "title": "KavaNet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">KavaNas</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">Network Controller</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "<h1 style=\"text-align:center; margin-top:10px\">KavaNet</h1>"
   }
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$KavaNas:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$KavaNas:9100\",job=\"K3S\"}",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$KavaNas:9100\",job=\"K3S\",sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$NetworkController:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"}",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Root",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$NetworkController:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$NetworkController:9100\",job=\"K3S\",sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$KavaNet:9100\",job=\"K3S\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"}",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Root",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$KavaNet:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$KavaNet:9100\",job=\"K3S\",sensor=\"temp0\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$master:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$master:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$master:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$master:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$master:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/srv/dev-disk-by-label-KavaNas\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/srv/dev-disk-by-label-KavaNas\",fstype!=\"rootfs\"})",
     "legendFormat": "KavaNas"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$NetworkController:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$NetworkController:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$NetworkController:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$NetworkController:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$NetworkController:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} - node_memory_SwapFree_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"}) / (node_memory_SwapTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} )) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$KavaNet:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$KavaNet:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$KavaNet:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$KavaNet:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$KavaNet:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} - node_memory_SwapFree_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"}) / (node_memory_SwapTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} )) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$KavaNas:9100\",job=\"K3S\",device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$KavaNas:9100\",job=\"K3S\",device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$NetworkController:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$NetworkController:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$NetworkController:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$NetworkController:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$NetworkController:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} - node_memory_SwapFree_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"}) / (node_memory_SwapTotal_bytes{instance=\"$NetworkController:9100\",job=\"K3S\"} )) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$KavaNet:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$KavaNet:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$KavaNet:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$KavaNet:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$KavaNet:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} - node_memory_SwapFree_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"}) / (node_memory_SwapTotal_bytes{instance=\"$KavaNet:9100\",job=\"K3S\"} )) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Current Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$KavaNas:9100\",job=\"K3S\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$KavaNas:9100\",job=\"K3S\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$KavaNas:9100\",job=\"K3S\"}) by (cpu))",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$master:9100\",job=\"K3S\"} * 100) / node_memory_MemTotal_bytes{instance=\"$master:9100\",job=\"K3S\"})",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/srv/dev-disk-by-label-KavaNas\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$KavaNas:9100\",job=\"K3S\",mountpoint=\"/srv/dev-disk-by-label-KavaNas\",fstype!=\"rootfs\"})",
     "legendFormat": "KavaNas"
    }
   ]
  }
 ]
}