# Use Node version 14
FROM node:14

# Create app directory within container
WORKDIR /usr/src/app

# Install app dependencies
# A wild card is used to ensure both package.json AND package-lock.json are copied 
COPY ./package*.json ./
COPY ./tsconfig.json ./

RUN npm install

# Copy across source folder
COPY ./src ./src

ENV CLUSTER=true


# RUN npm install -g nodemon

EXPOSE 1883
EXPOSE 9001
CMD ["npm", "start"]
# CMD ["node", "src/index.js"]